name: origin
dependencies:
  - python=3.11
  - originpro=1.1.10
  - numpy=2.2.3
  - pandas=2.2.3
  - pillow=11.1.0
  - PyGetWindow=0.0.9
  - PyRect=0.2.0
  - python-dateutil=2.9.0.post0
  - pytz=2025.1
  - six=1.17.0
  - tzdata=2025.1